export const CONFIG_JWT_SECRET = 'JWT_SECRET';
export const CONFIG_JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET';
export const CONFIG_JWT_ACCESS_TOKEN_EXPIRATION = 'JWT_ACCESS_TOKEN_EXPIRATION_TIME';
export const CONFIG_JWT_REFRESH_TOKEN_EXPIRATION = 'JWT_REFRESH_TOKEN_EXPIRATION_TIME';
export const CONFIG_JWT_REFRESH_TOKEN_EXPIRATION_SECONDS = 'JWT_REFRESH_TOKEN_EXPIRATION_TIME_SECONDS';
